const questions = [
  "60s, 70s, 80s, 90s: Which decade do you love the most and why?",
  "Are you a cat or dog person or neither? Why?",
  "Are you a good dancer?",
  "Are you a morning person or a night person?",
  "Are you a traveler or a homebody?",
  "Are you an early bird or night owl?",
  "Are you more productive at night or in the morning? Do you think it's possible to change and get used to another schedule?",
  "Are you sunrise, daylight, twilight, or nighttime? Why?",
  "Are some human lives worth more than others?",
  "As a child, what did you want to be when you grew up?",
  "Be honest, how often do you work from bed?",
  "Besides insects and spiders, what animals annoy you the most?",
  "Besides war and diplomacy, what would be the best way for countries to settle disputes?",
  "Best book you've ever read?",
  "Best professional development book you've ever read?",
  "Coffee or tea?",
  "Did you get good sleep today?",
  "Did your parents do a good job?",
  "Do you collect anything?",
  "Do you do things to make money, or do you make money to do things?",
  "Do you feel that you have conscious control over your beliefs?",
  "Do you have a dedicated office space at home?",
  "Do you have a favorite plant?",
  "Do you have more thoughts or more feelings?",
  "Do you have someone you feel comfortable talking to about everything?",
  "Do you love working from home or would you rather be in the office? Is there a balance of both that you like best?",
  "Do you prefer pens or pencils? Why?",
  "Do you think you could live without your smartphone (or other technology item) for 24 hours?",
  "Do you think you have a pretty good work-life balance? Why or why not?",
  "Do you think you rely too heavily on your phone? Why or why not?",
  "Does your current car have a name? What is it?",
  "Has there ever been a time when something so amazing or unexpected happened that it literally left you speechless for a time?",
  "Have you ever been told you look like someone famous, who was it?",
  "Have you ever completed anything on your bucket list?",
  "Have you ever dated someone who you felt was below your standards?",
  "Have you ever dated someone who you felt was way above your standards?",
  "Have you ever had a spiritual experience? If so, what it was like and what effects did it have on you?",
  "Have you ever met your idol or someone you revere greatly?",
  "How could carousels be spiced up so they are more exciting?",
  "How did you get that scar of yours?",
  "How did you spend the money from your very first job?",
  "How do you feel about clowns?",
  "How do you know if something is immoral?",
  "How do you like your eggs?",
  "How do you stay productive and motivated working virtually?",
  "How do you think you will be/act when you are old?",
  "How do you usually get your news?",
  "How good are you at drawing?",
  "How handy are you when it comes to fixing things?",
  "How into self-improvement are you?",
  "How into tech are you? Why?",
  "How many cups of coffee, tea, or beverage-of-choice do you have each morning?",
  "How often do you dance?",
  "How often do you think about your own death?",
  "How old do you feel inside?",
  "How well do you know your neighbors?",
  "How would you spend a million dollars? How about a billion?",
  "How would your friends describe you?",
  "If a movie was made of your life what genre would it be, who would play you?",
  "If a new volcano formed and the government had an online contest to see what it would be named, what name would you submit?",
  "If aliens landed on earth tomorrow and offered to take you home with them, would you go?",
  "If extraterrestrials landed on earth and offered to take you with them, would you go?",
  "If someone came up to you and said ''Hey, do that thing you do!'', what thing would pop into your head first?",
  "If the universe is just a simulation, what update or patch does it need?",
  "If you could add a word to the dictionary what would you add and what would it mean?",
  "If you could add anyone to Mount Rushmore who would it be; why?",
  "If you could be an animal, what animal would you be and why?",
  "If you could be any animal in the world, what animal would you choose to be?",
  "If you could be any sports personality who would it be and why?",
  "If you could be any supernatural creature, what would you be and why?",
  "If you could be guaranteed one thing in life (besides money), what would it be?",
  "If you could be immortal, what age would you choose to stop aging at and why?",
  "If you could be in any movie, what would it be and what character would you play?",
  "If you could be on a reality TV show, which one would you choose and why?",
  "If you could bring back any fashion trend what would it be?",
  "If you could change one thing about yourself what would you choose?",
  "If you could change places with anyone in the world, who would it be and why?",
  "If you could choose any historical figure to be your imaginary friend, who would it be and why?",
  "If you could choose any person from history to be your imaginary friend, who would it be and why?",
  "If you could choose any two famous people to have dinner with who would they be?",
  "If you could choose your age forever, what age would you choose and why?",
  "If you could choose your dreams, what would you prefer to dream about?",
  "If you could commit any crime and get away with it what would you choose and why?",
  "If you could do anything in the world as your career, what would you do?",
  "If you could eliminate one thing from your daily routine, what would it be and why?",
  "If you could go to Mars, would you? Why or why not?",
  "If you could hang out with any cartoon character, who would you choose and why?",
  "If you could have someone follow you around all the time, like a personal assistant, what would you have them do?",
  "If you could have the power of teleportation right now, where would you go and why?",
  "If you could instantly become an expert in something, what would it be?",
  "If you could kill any fashion trend forever what would it be?",
  "If you could learn one new personal skill, what would it be?",
  "If you could learn one new professional skill, what would it be?",
  "If you could live anywhere in the world for a year, where would it be?",
  "If you could live anywhere on this planet, where would you choose to live?",
  "If you could live in any country, where would you live?",
  "If you could magically become fluent in any language, what would it be?",
  "If you could meet any historical figure, who would you choose and why?",
  "If you could meet any living person for dinner, who would you pick and why?",
  "If you could pick up a new skill in an instant what would it be?",
  "If you could rename yourself, what name would you pick?",
  "If you could see one movie again for the first time, what would it be and why?",
  "If you could start a charity, what would it be for?",
  "If you could write a book that was guaranteed to be a best seller, what would you write?",
  "If you could write a book, what genre would you write it in? Mystery? Thriller? Romance? Historical fiction? Non-fiction?",
  "If you had 25 hours a day, how would you use your extra time?",
  "If you had a time machine, would go back in time or into the future?",
  "If you had to delete all but 3 apps from your smartphone, which ones would you keep?",
  "If you had to delete all but three apps from your smartphone, which ones would you keep?",
  "If you had to eat one meal every day for the rest of your life what would it be?",
  "If you had to eat one meal everyday for the rest of your life what would it be?",
  "If you had to lose all your memories which one would want to lose last?",
  "If you had to lose one of your senses, which would you choose to lose?",
  "If you had to play one album forever which one would it be?",
  "If you had to teach a class on one thing, what would you teach?",
  "If you left your current life behind and ran away to follow your dreams, what would you be doing?",
  "If you were a superhero what would your name be?",
  "If you were a superhero what would your superpower be and why?",
  "If you were a vegetable, what vegetable would you be and why?",
  "If you were a wrestler what would be your entrance theme song?",
  "If you were famous what would you be famous for?",
  "If you were famous, what would you be famous for?",
  "If you were featured on the local news, what would you most likely be on there for?",
  "If you were independently wealthy and didn't have to work, what would you do with your time?",
  "If you were left on a deserted island with either your worst enemy or no one, which would you choose? Why?",
  "If you were so wealthy you didn't need to work, what would you do with your time?",
  "If you were stranded on a desert island, what three items would you want to have with you?",
  "If you were to change your name, what name would you change to and why?",
  "Is there anything you're a fan of, that you never admitted to anybody?",
  "Is there anyone whose life you value more than your own?",
  "Popcorn or M&Ms?",
  "Say you're independently wealthy and don't have to work, what would you do with your time?",
  "Show us your office space!",
  "Teleportation or flying?",
  "Tell me about a time you were totally out of your element/comfort zone.",
  "The zombie apocalypse is coming, who are 3 people you want on your team?",
  "The zombie apocalypse is coming, who are three people you want on your team?",
  "What about becoming an adult caught you completely off guard?",
  "What about showers? Do you prefer morning or night?",
  "What apps do you use most?",
  "What are common misconceptions about your job?",
  "What are some films that would make it on to your top 50 list of movies?",
  "What are some of the dumbest misadventures you've been on?",
  "What are some of your favorite games to play?",
  "What are some of your favorite holiday traditions that you did while growing up?",
  "What are some of your favorite scenes from movies?",
  "What are some of your guilty pleasures?",
  "What are two of your favorite snacks?",
  "What are you best at fixing?",
  "What are you grateful for?",
  "What are you hilariously bad at?",
  "What are you kind of snobby about?",
  "What are you reading right now?",
  "What are your three favorite drinks?",
  "What are your three favorite foods?",
  "What assumption you made went hilariously wrong?",
  "What big problem do you think technology will solve next?",
  "What book did you read that changed your life the most?",
  "What book had the most significant impact on you?",
  "What book, movie read/seen recently you would recommend and why?",
  "What brands do you love/hate the most?",
  "What breed of dog would you be?",
  "What card or board games do you like to play?",
  "What catchy jingle or bit of advertising has stuck with you all these years?",
  "What clothing item would make you walk out on a date if someone wore it?",
  "What company or brand did you love until they betrayed your trust?",
  "What could movie theaters do to improve the experience of going there?",
  "What crossed way too far into the uncanny valley for you?",
  "What culture would you like to learn more about?",
  "What did you eat for breakfast?",
  "What did you have for breakfast this morning?",
  "What did you name your first car?",
  "What did your teachers and parents say would be really important when you grew up, but it hasn't been?",
  "What difficult or painful experience would you recommend to everyone?",
  "What do you buy way more of than most people?",
  "What do you do to unwind after a hard day?",
  "What do you geek out about?",
  "What do you highly recommend to most people you meet?",
  "What do you rebel against?",
  "What do you resent paying for most?",
  "What do you think the ideal age to be is?",
  "What do you usually do on your commute to work?",
  "What do you want to do when you retire?",
  "What do you wish someone taught you a long time ago?",
  "What do you wish was illegal?",
  "What do you wish your phone could do?",
  "What does your favorite shirt look like?",
  "What does your morning routine look like when working from home?",
  "What does your perfect breakfast look like?",
  "What does your perfect burger or sandwich have in it?",
  "What does your typical work from home uniform look like?",
  "What fashion trend needs to be brought back?",
  "What fictional family would you be a member of?",
  "What fictional world or place would you like to visit?",
  "What food do you love that a lot of people might find a little odd?",
  "What food is underrated or underappreciated?",
  "What fruit or vegetable would you most want to be?",
  "What hard time in your life left you a better person after it was finished?",
  "What has really taken a toll on you?",
  "What has taken you the longest to get good or decent at?",
  "What hobby would you be a lot of fun to get into?",
  "What household chore do you actually enjoy?",
  "What incredibly common thing have you never done?",
  "What is a lie you wish you stop telling yourself?",
  "What is one article of clothing that someone could wear that would make you walk out on a date with them?",
  "What is something you do better than most people and something you do worse than most people?",
  "What is the best event you've attended?",
  "What is the best pair of shoes you have owned?",
  "What is the best perk you have ever enjoyed at a job?",
  "What is the best thing you have ever bought?",
  "What is the biggest mistake you've made at work?",
  "What is the biggest obstacle towards world's peace?",
  "What is the greatest current existential threat to humanity?",
  "What is the last goal you achieved?",
  "What is the meaning of life?",
  "What is the meaning of your name?",
  "What is the most amazing fact you know?",
  "What is the most clever or funniest use of advertising you've seen?",
  "What is the most controversial opinion you hold?",
  "What is the most stressful TV show or movie you watched?",
  "What is the most tedious and/or the most exciting sport to watch?",
  "What is the most unique or silliest problem you have going on in your life at the moment?",
  "What is the weirdest food combination you've made and tried?",
  "What is your absolute dream job?",
  "What is your cellphone wallpaper?",
  "What is your favorite breakfast food?",
  "What is your favorite dessert?",
  "What is your favorite genre of movie? Why?",
  "What is your favorite holiday and why?",
  "What is your favorite item you've bought this year?",
  "What is your favorite magical or mythological animal?",
  "What is your favorite meal to cook and why?",
  "What is your favorite musical instrument and why?",
  "What is your favorite season of the year and why?",
  "What is your favorite sport to watch and why?",
  "What is your favorite television network?",
  "What is your favorite time of the day and why?",
  "What is your favorite TV show?",
  "What is your most used emoji?",
  "What kind of art do you appreciate the most?",
  "What kind of challenges are you facing these days?",
  "What kind of people do you most enjoy hanging out with?",
  "What kind of physical activities do you like doing?",
  "What languages do you know how to speak?",
  "What luxury is totally worth the price?",
  "What makes you feel old when you think about it?",
  "What motivates you?",
  "What movie have you seen recently that you would recommend and why?",
  "What movie never gets old no matter how many times you've seen it?",
  "What music do you put on when you want to get pumped?",
  "What period would be the best to be born in?",
  "What pets did you have growing up?",
  "What public spaces do you feel most comfortable in? (Library, bar, park, mall, stadium, etc.)",
  "What recent trend are you totally on board with?",
  "What rule do you wish they would introduce into your favorite sport?",
  "What scene in a movie always gives you goosebumps every time you watch it?",
  "What season would you be?",
  "What skill do you think everyone should have?",
  "What skill or talent would you most like to learn?",
  "What slang are you really happy went out of fashion?",
  "What smell do you hate that doesn't seem to bother other people?",
  "What songs would be played on a loop in hell?",
  "What sport do you wish you knew more about?",
  "What sport would you compete in if you were in the Olympics?",
  "What subjects should be taught in school but aren't?",
  "What takes a lot of time but is totally worth it?",
  "What tells you the most about a person?",
  "What topic could you give a 20-minute presentation on without any preparation?",
  "What toy did you hate most as a child?",
  "What TV show are you hooked on or were recently hooked on?",
  "What unusual traits do you find attractive in a romantic partner?",
  "What useless facts do you know?",
  "What was something courageous you've (in person) seen someone do?",
  "What was something you thought would be easy until you tried it?",
  "What was the country you last visited outside of United States?",
  "What was the craziest theme park or fair ride you've been on?",
  "What was the first thing you bought with your own money?",
  "What was the funniest thing you've seen recently online?",
  "What was the last thing you were really excited about?",
  "What was the scariest movie you've seen?",
  "What was the worst haircut you ever had?",
  "What was the worst job you ever had?",
  "What was the worst style choice you ever made?",
  "What was your best vacation?",
  "What was your favorite game to play as a child?",
  "What was your funniest or worst experience with a dentist?",
  "What was your least favorite food as a child? Do you still hate it or do you love it now?",
  "What was your worst haircut experience?",
  "What wastes the most time in your day to day life?",
  "What website or app doesn't exist, but you really wish it did?",
  "What weird quirks did you pick up from your parents?",
  "What weird thing do you have nostalgia for?",
  "What well-known person does the most good for the world?",
  "What were your favorite television shows when you were growing up?",
  "What workers have the worst jobs?",
  "What works of art have really made an impression on you?",
  "What would be the most surprising scientific discovery imaginable?",
  "What would the title of your autobiography be?",
  "What would you change if you were in charge of the company you work for?",
  "What would you do with your 15 minutes of fame?",
  "What would you like to be known/remembered for?",
  "What would you like to do when you retire?",
  "What would your dream house be like?",
  "What would your superpower be and why?",
  "What would your talent be if you were Miss or Mister World?",
  "What, in your opinion, is the most amazing animal?",
  "What's a problem you have, that might be entirely unique to you?",
  "What's is one thing we don't know about you?",
  "What's one career you wish you could have?",
  "What's one thing we could do to improve our virtual meetings?",
  "What's something that a lot of people are missing out on because they don't know about it?",
  "What's something that was once important but is now becoming less and less relevant?",
  "What's something you're looking forward to?",
  "What's the best advice you've ever heard?",
  "What's the best backhanded compliment you've heard / can think of on the spot?",
  "What's the best cake you've ever eaten?",
  "What's the best concert you've been to and why was it so good?",
  "What's the best day you've had recently?",
  "What's the best location to fully enjoy a good cup of coffee?",
  "What's the best or worst prank you've played on someone?",
  "What's the best piece of advice you have ever been given?",
  "What's the best piece of advice you've ever been given?",
  "What's the best sports game you've been to?",
  "What's the best thing you've got going on in your life at the moment?",
  "What's the best way to stay young?",
  "What's the biggest adventure you've been on?",
  "What's the biggest vehicle you've driven?",
  "What's the hardest part about working virtually for you? The easiest?",
  "What's the last great TV show or movie you wanted?",
  "What's the longest trip you've been on?",
  "What's the most amazing natural occurrence you've witnessed?",
  "What's the most annoying machine you must deal with regularly?",
  "What's the most creative thing you've done?",
  "What's the most delightful hotel or house you've stayed in on vacation?",
  "What's the most embarrassing fashion trend you used to rock?",
  "What's the most out-of-character thing you've ever done?",
  "What's the most outdated piece of tech you still use regularly?",
  "What's the most unique shop or restaurant you've been in?",
  "What's the noblest endeavor a person can dedicate their life to?",
  "What's the scariest horror movie or horror book monster?",
  "What's the silliest thing you are pretty good at?",
  "What's the strangest name someone you have met had?",
  "What's the weirdest food you've ever eaten?",
  "What's the weirdest way you have met someone?",
  "What's the worst advice you've been given?",
  "What's your best \"my coworkers are crazy\" story?",
  "What's your best scar story?",
  "What's your best scary story?",
  "What's your caffeinated beverage of choice? Coffee? Cola? Tea?",
  "What's your drink of choice? (Either alcoholic or non.)",
  "What's your earliest memory?",
  "What's your favorite breakfast cereal?",
  "What's your favorite car that you've owned?",
  "What's your favorite color and how does that color make you feel?",
  "What's your favorite family tradition?",
  "What's your favorite flower or plant?",
  "What's your favorite food combination?",
  "What's your favorite international food?",
  "What's your favorite island that you've visited?",
  "What's your favorite line from a book or a movie?",
  "What's your favorite month?",
  "What's your favorite Olympic sport to watch?",
  "What's your favorite place of all the places you've travelled?",
  "What's your favorite place you've ever visited?",
  "What's your favorite sandwich and why?",
  "What's your favorite scent?",
  "What's your favorite thing about the area/city/state you live in?",
  "What's your favorite tradition or holiday?",
  "What's your favorite type of day? (weather, temp, etc.)",
  "What's your favorite way to get in some exercise?",
  "What's your favorite way to spend time outdoors?",
  "What's your favorite way to waste time online?",
  "What's your idea of a great day?",
  "What's your idea of a great party?",
  "What's your number one tip for combating distractions when working from home?",
  "When is the most interesting period in history?",
  "When someone finds out what you do, or where you are from, what question do they always ask you?",
  "When you die, what do you want to be remembered for?",
  "Where are five places you really want to visit before you die?",
  "Where do you work most frequently from at home? Your office? Your kitchen table? The backyard? Your bed?",
  "Where have you traveled to?",
  "Where's the most surreal area you been to?",
  "Where's your favorite place to nap?",
  "Which actor would you want to play you in the movie about your life?",
  "Which band / artist - dead or alive would play at your funeral?",
  "Which life lesson you learned that would be most important for the people in this room to hear?",
  "Which song can you listen to all day long?",
  "Which technology should not have been invented?",
  "Who had the most influence on you growing up?",
  "Who has been your most interesting/confusing/annoying neighbor?",
  "Who is the better businessman or business woman and why?",
  "Who is the funniest person in your family?",
  "Who is the most competitive person you know?",
  "Who is the most gifted person you know?",
  "Who is the most intelligent or creative person you know?",
  "Who is the most interesting person you've met and talked with?",
  "Who is the most interesting stranger you've met?",
  "Who is the oldest person you know personally? What interesting stories have they told you?",
  "Who is your alter ego?",
  "Who is your favorite Disney hero or heroine? Would you trade places with them?",
  "Who was your childhood actor/actress crush?",
  "Who was your favorite teacher?",
  "Would you ever try space tourism, if you had the money for it?",
  "Would you go with aliens if they beamed down to Earth?",
  "Would you marry or date a fictional character? Which one?",
  "Would you rather always be slightly late or super early?",
  "Would you rather be a superhero or the world's best chef?",
  "Would you rather be able to run at 100 miles per hour or fly at 10 miles per hour?",
  "Would you rather be an Olympic gold medallist or an astronaut?",
  "Would you rather be invisible or be able to read minds?",
  "Would you rather be the funniest or smartest person in the room?",
  "Would you rather give up your smartphone or your computer?",
  "Would you rather have invisibility or flight?",
  "Would you rather live in the ocean or on the moon?",
  "Would you rather live where it only snows or the temperature never falls below 100 degrees?",
  "Would you rather live without heat and AC or live without social media?",
  "Would you rather lose all of your money or all of your pictures?",
  "Would you rather lose your ability to sing or to swear?",
  "Would you rather meet your travel back in time to meet your ancestors or to the future to meet your descendants?",
  "Would you rather spend time with other people or at home alone?",
  "Would you rather watch a movie on your TV at home or on the big screen in the theater, and why?",
  "Would you ride in a zeppelin if given a chance?",
  "Would you show your browsing history to everybody present? What if incognito was included too?",
  "Who do you hate most, and who do you love most?",
  "You can have an unlimited supply of one thing for the rest of your life, what is it? Sushi? Scotch Tape?",
  "You can have anyone fictional as your imaginary friend, who do you choose and why?",
  "You have to sing karaoke, what song do you pick?",
  "You have your own late night talk show, who do you invite as your first guest?",
  "You're going sail around the world, what's the name of your boat?"
  
  // New questions May 2025
  // Hypotheticals
  "If you could eliminate one emotion forever, which would you choose?",
  "If you had to replace your hands with objects, what would you pick?",
  "If historical figures had social media, who would be most entertaining?",
  "If you could instantly master any musical instrument, which would you choose?",
  "If you could communicate with one animal species, which would it be?",
  "If money was no object, what would your perfect weekend look like?",
  "If you could solve one global problem instantly, which would you pick?",
  "If you had to wear one outfit forever, what would it look like?",
  "If you could bring one fictional character to life, who would it be?",
  "If you could live in any video game world, which would you choose?",

  // Food & Drink
  "What condiment best represents your personality?",
  "What food combination should be illegal?",
  "What's your controversial food opinion?",
  "Sweet breakfast or savory breakfast?",
  "What meal reminds you of childhood?",
  "What's your ultimate comfort food?",
  "What restaurant could you eat at every day?",
  "What's the strangest food you've enjoyed?",
  "What food trend needs to disappear?",
  "What ingredient makes everything better?",

  // Technology
  "What outdated technology do you still love?",
  "What tech innovation scares you most?",
  "What app has most improved your life?",
  "What website deserves more recognition?",
  "What sci-fi technology should exist by now?",
  "What tech company fascinates you most?",
  "What's your biggest tech pet peeve?",
  "What digital tool couldn't you live without?",
  "What emerging technology excites you most?",
  "What tech myth do people still believe?",

  // Travel & Adventure
  "What's your perfect vacation weather?",
  "What travel destination exceeded expectations?",
  "What's your ideal travel companion?",
  "What's the most breathtaking view you've seen?",
  "What travel scam have you encountered?",
  "What souvenir do you always bring back?",
  "What's your airport survival strategy?",
  "What travel hack changed your life?",
  "What country's cuisine surprised you most?",
  "What's your favorite mode of transportation?",

  // Personality & Preferences
  "What's your most used emoji?",
  "What song always puts you in a good mood?",
  "What fictional character do you relate to?",
  "What smell triggers strong memories?",
  "What childhood toy do you miss most?",
  "What useless talent do you have?",
  "What phrase do you overuse?",
  "What makes you instantly trust someone?",
  "What makes you roll your eyes immediately?",
  "What personality trait are you proud of?",

  // Work & Productivity
  "What's your best productivity trick?",
  "What office supply brings you joy?",
  "What career path did you narrowly escape?",
  "What's your favorite work-from-home hack?",
  "What meeting should be eliminated?",
  "What job would you be terrible at?",
  "What's your dream work environment?",
  "What professional skill do you want to develop?",
  "What's your best time management tip?",
  "What industry secret should people know?",

  // Science & Nature
  "What natural phenomenon fascinates you?",
  "What scientific discovery changed your worldview?",
  "What animal deserves more respect?",
  "What plant best represents your personality?",
  "What space fact blows your mind?",
  "What environmental issue concerns you most?",
  "What everyday chemical deserves more attention?",
  "What medical breakthrough do you hope to see?",
  "What evolutionary trait could humans use?",
  "What weather pattern intrigues you?",

  // Arts & Culture
  "What obscure artist deserves fame?",
  "What museum exhibit stuck with you?",
  "What book character would you befriend?",
  "What song lyrics speak to your soul?",
  "What painting would you live inside?",
  "What genre of music needs revival?",
  "What playwright best captures modern life?",
  "What dance style best expresses joy?",
  "What architectural style moves you?",
  "What poetic form matches your personality?",

  // History & Future
  "What historical era is misunderstood?",
  "What future technology are you dreading?",
  "What ancient invention still amazes you?",
  "What historical figure needs a biopic?",
  "What modern convenience would shock past-you?",
  "What future trend are you predicting?",
  "What archaeological find excited you most?",
  "What historical mystery needs solving?",
  "What past decade had the best music?",
  "What vintage trend should return?",

  // Philosophy & Ethics
  "What moral dilemma keeps you up?",
  "What ethical line shouldn't be crossed?",
  "What human right needs protection?",
  "What philosophical question lacks answer?",
  "What social contract needs updating?",
  "What cultural practice deserves respect?",
  "What personal boundary is non-negotiable?",
  "What truth do people avoid?",
  "What common practice will future generations condemn?",
  "What belief did you outgrow?",

  // "Would You Rather" Variations
  "Would you rather know history or future?",
  "Would you rather speak all languages or talk to animals?",
  "Would you rather lose sight or hearing?",
  "Would you rather explore space or oceans?",
  "Would you rather be respected or loved?",
  "Would you rather have fame or fortune?",
  "Would you rather time travel or teleport?",
  "Would you rather lose memory or imagination?",
  "Would you rather meet ancestors or descendants?",
  "Would you rather be bulletproof or read minds?",

  // Pop Culture
  "What canceled show deserves revival?",
  "What movie sequel ruined the original?",
  "What celebrity deserves their fame?",
  "What viral trend confused you?",
  "What book-to-movie adaptation failed?",
  "What video game deserves movie treatment?",
  "What band needs reunion tour?",
  "What meme makes you laugh every time?",
  "What Oscar winner was undeserving?",
  "What fictional world would you inhabit?",

  // Relationships & Social
  "What friendship trait matters most?",
  "What red flag is often ignored?",
  "What green flag attracts you?",
  "What relationship advice would you give?",
  "What social custom needs retirement?",
  "What conversation topic excites you?",
  "What makes someone good company?",
  "What friendship ended surprisingly?",
  "What compliment meant the most?",
  "What family tradition is sacred?",

  // Personal Growth
  "What fear did you overcome?",
  "What lesson took longest to learn?",
  "What childhood belief was magical?",
  "What habit transformed your life?",
  "What outdated belief did you discard?",
  "What self-care practice works best?",
  "What limiting belief holds people back?",
  "What personal achievement makes you proud?",
  "What mindfulness practice helps you?",
  "What life skill isn't taught enough?",

  // Humor & Fun
  "What dad joke makes you laugh?",
  "What conspiracy theory is entertaining?",
  "What reality show would you dominate?",
  "What cartoon law of physics should exist?",
  "What sitcom character are you?",
  "What ridiculous product would you invent?",
  "What parody account is genius?",
  "What comedy movie quote lives in your head?",
  "What meme describes your life?",
  "What fictional job would be terrible?",

  // Seasonal & Holiday
  "What holiday tradition is sacred?",
  "What seasonal smell evokes nostalgia?",
  "What Halloween costume won you awards?",
  "What Thanksgiving dish causes drama?",
  "What winter activity brings joy?",
  "What summer memory is cherished?",
  "What holiday movie is overrated?",
  "What autumn ritual matters most?",
  "What spring cleaning task gets skipped?",
  "What New Year's resolution stuck?",

  // Education & Learning
  "What subject should be mandatory?",
  "What lesson from school proved useful?",
  "What teacher changed your perspective?",
  "What skill is surprisingly easy?",
  "What academic field needs funding?",
  "What learning method works best?",
  "What historical event needs reexamination?",
  "What scientific field fascinates you?",
  "What language sounds most musical?",
  "What educational game was best?",

  // Health & Wellness
  "What wellness trend actually works?",
  "What exercise do you hate?",
  "What health myth needs debunking?",
  "What mental health practice helps?",
  "What alternative therapy intrigues?",
  "What sleep habit improved life?",
  "What nutrition advice is bogus?",
  "What pain relief method works?",
  "What fitness fad deserves revival?",
  "What health measurement is overrated?",

  // Home & Lifestyle
  "What household chore is therapeutic?",
  "What decor style feels like home?",
  "What kitchen gadget is essential?",
  "What cleaning product is magic?",
  "What DIY project succeeded?",
  "What organizational system works?",
  "What garden plant brings joy?",
  "What neighborhood feature matters?",
  "What furniture piece is sacred?",
  "What home smell signifies comfort?",

  // Money & Finance
  "What frugal habit saves money?",
  "What luxury is worth the cost?",
  "What financial advice is outdated?",
  "What investment paid off?",
  "What money myth persists?",
  "What purchase brought happiness?",
  "What budgeting method works?",
  "What financial fear haunts you?",
  "What economic indicator matters?",
  "What retirement dream persists?",

  // Sports & Games
  "What Olympic sport is underrated?",
  "What board game causes rivalry?",
  "What sports rule needs changing?",
  "What video game soundtrack slaps?",
  "What athletic feat amazes you?",
  "What game show could you win?",
  "What sports movie was most accurate?",
  "What childhood game was best?",
  "What card game strategy works?",
  "What esport deserves recognition?",

  // Language & Communication
  "What untranslatable word is needed?",
  "What communication skill matters?",
  "What idiom makes no sense?",
  "What language sounds angry?",
  "What grammar rule can disappear?",
  "What nonverbal cue is universal?",
  "What dialect is music to ears?",
  "What speech habit annoys?",
  "What compliment sounds best?",
  "What conversation topic energizes?",

  // Fashion & Style
  "What fashion trend needs revival?",
  "What accessory elevates any outfit?",
  "What shoe style is overrated?",
  "What fabric feels luxurious?",
  "What style era inspires you?",
  "What outfit gives confidence?",
  "What fashion rule should die?",
  "What celebrity style icon impresses?",
  "What clothing comfort is essential?",
  "What pattern sparks joy?",

  // Transportation
  "What vehicle innovation excites?",
  "What road trip snack is essential?",
  "What public transport improvement needed?",
  "What flying experience was memorable?",
  "What car feature is overrated?",
  "What nautical transport intrigues?",
  "What bike upgrade matters?",
  "What space vehicle design is coolest?",
  "What train journey is dreamy?",
  "What futuristic transport needed?",
];

export default (_req, res) => {
  res.statusCode = 200;
  res.json({ 
    question: questions[Math.floor(Math.random()*questions.length)]
  });
}
